service: optin-sms-api

provider:
  name: aws
  runtime: nodejs10.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: us-east-1

environment:
  TWILIO_ACCOUNT_SID: ${env:TWILIO_ACCOUNT_SID}
  TWILIO_AUTH_TOKEN: ${env:TWILIO_AUTH_TOKEN}
  TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}

functions:
  sendText:
    handler: handler.sendText
    events:
      - http:
          path: /sendText
          method: post
          integration: lambda
          cors: true

plugins:
 - serverless-offline
 - serverless-dotenv-plugin